- tags/tags.toml
> Add "bot about me" and "botception" tags, update link in discord-buttons tag

- tags/tags.toml
* shorten limit tags to point to dapi docs
* fix typos and grammar
* add maria and sqlite to database
* add keyword dnw to no-work
* delete await in foreach
* add v13 changes
> chore: tags

- tags/tags.toml
> new tag: filter

- tags/tags.toml
Redo of pr #9, as I screwed something up.
> Add event-deprecation tag

- tags/tags.toml
I found a typo. Then I found more typos. Now I made this pull request!
> fix(tags): Correct various typos

- package-lock.json
- package.json
- src/deployFunctions/deployGlobal.ts
- src/functions/docs.ts
- tags/tags.toml
(https://github.com/TeeSeal/discord.js-docs/pull/14)
> chore: replace master with main

- src/functions/node.ts
- src/util/constants.ts
> fix(node): fixed /node slashie

- tags/tags.toml
This PR adds `js` highlighting to the code block in `sharding` tag
> fix: added js highlighting in code block

- tags/tags.toml
A smol tag for the footer and author deprecation warning.
> Tag: footer & author

- tags/tags.toml
This PR fixes the link for the embed limits tag.
> fix: Fix embed limits link

- tags/tags.toml
Forgot to change this one on last commit
> Token Reset Change

- tags/tags.toml
Updated the token tag to add the new Reset Token of discord
> Add new discord look to image

- tags/tags.toml
These tags should not be linking the main documentation.
> fix: Use stable links

- tags/tags.toml
a tag with information on becoming a sponsor of discord.js
> tag: djs-sponsor

- tags/tags.toml
This PR adds a new tag that shows why someone has duplicate commands, and how to fix it
> tag: duplicate-commands

- tags/tags.toml
Not every name was changed to PascalCase
> Fix case of names

- src/functions/tag.ts
- src/index.ts
- src/util/interactionOptions.ts
- src/util/respond.ts
Some rules were being disabled despite nothing being affected by them, a non-null assertion operator had no effect, a string is being stringified... they are unnecessary.
> refactor: Remove unnecessary things

- tags/tags.toml
Add a tag for the generic in `ActionRowBuilder`
> tag: generic-actionrow

- tags/tags.toml
Discussed in discord
> https://canary.discord.com/channels/222078108977594368/1007612252486119426/1007612252486119426
> feat(tags): `voice-debug` tag

- tags/tags.toml
The link pointed to the old and archived docgen repo
Also ads a line bc yes
> fix(tags:docgen): update link to the monorepo

- src/functions/algoliaResponse.ts
- src/functions/autocomplete/docsAutoComplete.ts
- src/functions/docs.ts
- src/functions/mdn.ts
- src/functions/node.ts
- src/functions/tag.ts
- src/handling/handleApplicationCommand.ts
- src/interactions/discorddocs.ts
- src/interactions/docs.ts
- src/interactions/guide.ts
- src/interactions/invite.ts
- src/interactions/mdn.ts
- src/interactions/node.ts
- src/interactions/tag.ts
> feat: ephemeral reply option

- tags/tags.toml
Same reason as in:
- https://github.com/discordjs/guide/pull/1458
> refactor(filter): explicit collector filter parameter

- tags/tags.toml
For a while now, these links have been invalid. This fixes them.
> fix(tags): Update documentation links

- tags/tags.toml
This PR puts the entire error in the codeblock formatting.
> chore(tags): format error properly

- src/functions/node.ts
- src/interactions/node.ts
This PR updates the node versions for the `node` command with the current [release schedule](https://github.com/nodejs/release#release-schedule)
> chore: update node versions for node command

- src/functions/node.ts
> fix(node): proper url generation

- tags/tags.toml
Just include user id with a link to Discord article on how to find different ids, and update crawl's username to the new system.
> feat(tags): update djs-sponsor

- tags/tags.toml
a lot of questions are about voice channel statuses, or other undocumented features, which we do not support since these are undocumented, but people keep asking why
> add undocumented features tag
