- tags/tags.toml
Added a link to an SQLite tutorial; it's a sister site to the PG tutorial.  It's set up in the same manner and is very helpful.
> Add SQLite tutorial

- tags/tags.toml
`Client#setTimeout` has been removed in v13, so this tag should be updated to use a non-deprecated/deleted method.
> Fix delete-timeout example

- tags/tags.toml
This PR bumps the node version in the update tag to 16 and adds an additional alias for improved laziness.
> chore: bump node version tag

- tags/tags.toml
This pr bumps the ver (again), to .6 as that was a security release and thus a lower minor ver is not recommended.
> chore: bump minor node ver in tag to 16.6

- tags/tags.toml
With DJS v13 needing AbortController in Node 16 I think it'll be a good thing to have an alias for that.
Tag keywords are case insensitive I assume? Otherwise I'll add it as `AbortController`.
> feat(tags): add `abortcontroller` alias for `node-version`

- src/workflowFunctions/validateTags.ts
- tags/tags.toml
Discord embeds masked links in the `[label](link)` format. they thus have to be escaped as `[label](<link>)` as mentioned in the README. However, this is an easy-to-miss oversight in PR's. This PR adds validation for links (code blocks are excluded to allow the explanation of the syntax within tags without blocking the validation)
> feat(tags): validate masked links to be escaped

- tags/tags.toml
Remove the line in the timers tag that references the Client methods, as they were removed in v13.
> Update timers tag

- tags/tags.toml
Updated the link to point to the new area where the limits are documented.
> chore: Use new url for interactions

- tags/tags.toml
Improved diff code-block to more precisely show the changes necessary to replace the old `MessageEmbed#attachFiles` method.
> Fixed embed-files tag

- package-lock.json
- package.json
This will fix the issue of embedded links not being markdown escaped as
found by Souji when testing, specifically when searching `TimestampStylesString`
which would embed a link to discord.com.
> fix: update discordjs-docs-parser lib to fix a formatting issue in `/djs`

- tags/tags.toml
With the new change of discord.js's main repository changing to a monorepo, the documentation URL path has changed with it.
- Old: https://discord.js.org/#/docs/main
- New: https://discord.js.org/#/docs/discord.js
While [this commit](https://github.com/discordjs/website/commit/c82fe530a9e6e8aa60e7ab9c0e8570f85298a001) allowed `main` as a fallback, it is still a fallback at the end of the day. This pull request changes all old paths to new paths that are in the `stable` or `main` branch.
---
A VSCode indexed search has been done with the following queries:
- https://discord.js.org/#/docs/main/main
- https://discord.js.org/#/docs/main/stable
Which is then replaced with these respectively:
- https://discord.js.org/#/docs/discord.js/main
- https://discord.js.org/#/docs/discord.js/stable
> fix: use new documentation path

- tags/tags.toml
We should generally avoid linking to discord messages as source of information, if there is a better source (dev policy, in this case)
> chore(tags): dev policy as source for self-invite

- tags/tags.toml
A tag showing that Discord IDs must be represented as strings
> Tag: number-id

- src/functions/docs.ts
Closes #48 
An alternative option would be to specifically check for interfaces and not hyperlink them but they aren't really shown in documentation so I'm unsure if that would have much point
> chore: remove `implements` as `interface`(s) are not shown in documentation

- package.json
- src/functions/algoliaResponse.ts
- yarn.lock
This will ensure that entities such as `&#x27;` get properly decoded to `'`. Noticed it here: https://discord.com/channels/222078108977594368/222197033908436994/995710742277935204
(Added package is from https://github.com/mathiasbynens. Wouldn't normally just add a dependency for this but Mathias is an exception as a dev IMHO)
> fix: decode HTML entities

- tags/tags.toml
- The links are taken from https://dis.gd/testclients
- The invite to Discord Testers has been replaced with https://dis.gd/BugReport
> chore(canary): Update information

- tags/tags.toml
Updated `bot-invite` tag to reflect the (not so) recent change, where the 2 options are essentially either `bot` scope or `application.commands`, and they both result in having `application.commands` anyway. [Our news msg link](https://canary.discord.com/channels/222078108977594368/992166350640386090/996100739510304809).
Updated `all-intents` tag to have actually comprehensible first bullet point, and reworded the second point so that it reads more as "new stuff gets added but the number stays the same" and not "discord removed an intent from this number". Plus that comma there was weird anyway.
> chore: Update tags

- tags/tags.toml
This forces the locale to English (US), which may not be desired for non-English (US) users. Omitting the locale leaves it to the user's preference.
> refactor: Remove locales from support URLs

- PRIVACY.md
- package.json
- src/interactions/discorddocs.ts
- tags/tags.toml
- discord.js capitalisation
- Discord capitalisation
- WebSocket capitalisation
- Node.js capitalisation
- npm capitalisation
- "sever" typo in the privacy policy
- Other miscellaneous changes
> fix: Wording and typos

- tags/tags.toml
Preferring use of `StringSelectMenuBuilder` as `SelectMenuBuilder` is deprecated.
> fix: Update select menu usage

- tags/tags.toml
Windows Build Tools and Python can both be installed through the official Node.js installer (tested v12 installer) and because of that the windows-build-tools package has been deprecated and has been labeled deprecated and is there as option 2.
> tags: update node-opus

- .gitignore
- src/util/constants.ts
- tags/tags.toml
- `API_BASE_DISCORD_APLICATIONS` had a typo, but this constant was not used. It was therefore removed.
- "authentification" is not a word (this is a common misconception).
Also added .DS_Store to .gitignore.
> chore: Typos

- src/functions/autocomplete/docsAutoComplete.ts
- src/interactions/docs.ts
This PR removes the `rpc` subcommand from `/docs`, since there are no longer docs for `rpc`
> chore: remove rpc subcommand

- src/interactions/docs.ts
Simplifies the whole file, because every subcommand had the same options
Adds missing hide option to `discord-js-dev`
> chore: use base options in docs command

- tags/tags.toml
Change the tag to use `Interaction` instead of `Message`, as the general use case has changed since the tag was first written.
> chore (tags): Update "matching parameters" tag

- tags/tags.toml
Add a line detailing how most events in a cached guild will have both a `User` and a `GuildMember` available.  I think the conversion of user -> member via fetching introduces a poor example for users in support and they'll implement needless code, when their case will often have the member present, eg `Message#author` and `#member`, `Interaction#options#getUser` and `#getMember`.
> chore(tags): Update member-user tag

- tags/tags.toml
Updates the required nodejs version to 16.11.0, since the latest release v14.12.1 requires it when using typescript
> chore(tags): update required nodejs version

- tags/tags.toml
only real ones remember when one made reports via zendesk
> chore: remove /report from not-discord tag

- tags/tags.toml
`ClientOptions.restRequestTimeout` was changed to `RESTOptions.timeout` in v14 as we now use /rest.
I'm considering adding that this can be added to `ClientOptions` through `{ rest: { timeout: ... } }` too, not sure.
> refactor(abort): update timeout to v14 equivalent

- tags/tags.toml
Fixed the buttons link in `third-party-libraries` tag and as the guide doesn't have separate sections for responding to buttons and select menus anymore, I've replaced buttons and select menus with message components.
> fix(tags): update invalid guide links

- tags/tags.toml
> chore: Update Discord links

- .prettierrc.json
- tags/tags.toml
i added this tag since this is a very common question
> Add invite-tracker tag

- tags/tags.toml
If this tag is given to someone, it's because they're using an outdated Node.js version. Instead of telling them to update to a specific version which involves updating this tag as time goes by, we should instruct them to use the LTS version which will be enough for discord.js.
> feat: Update Node.js version to LTS

- tags/tags.toml
Updates the documentation links to the new website.
> feat: Update documentation links

- tags/tags.toml
> feat(tags): add relative paths base tag

- tags/tags.toml
A frequently recurring issue are network issues, with these being the 3 most common error messages
> Add network-issues tag

- package.json
- tags/tags.toml
Message got moved into its own class, thus the url changed
> Edit embed-limits link

- tags/tags.toml
new tag added for the deprecation warning of ephemeral in 14.17, as well as for the 50240 (You cannot remove this app's Entry Point command ...) error.
Removed the partial-group-dm tag as this was resolved in 14.16.2
> Ephemeral tag

- .github/workflows/validate.yml
- .github/workflows/validateWithLinks.yml
- Using Node.js22
- `--frozen-lockfile` is a legacy flag that will be removed in the future (`--immutable` is the standard). Anyway, this is not needed as in CI environments, [`--immutable` is the default](https://yarnpkg.com/cli/install)
> ci: Update miscellaneous workflow code

- tags/tags.toml
Will use their preferred locale instead.
> fix: Remove locales from links
